### ISSUE TITLE
Information: Cannot load MUGEN hook on MUGEN 1.1 via Linux/Wine

### ISSUE THREAD

**Issue by cyliamargatroid** [ermaccer/mugenhook#11]
I know this is only supported on any Actual Windows Platform.

**Comment by ermaccer** [comment]
https://github.com/ThirteenAG/WidescreenFixesPack/issues/207 
Maybe this will help?

**Comment by Tabris666** [comment]
i use wine on my other linux pc and works fine,did you install everything as you are supposed to.
normally once you install wine you have to install the following.
.- directx9
.- c++ runtime libraries (all of them)
.- net framework
i had the problem of mugen no starting but after i installed everyhting mugen run without problems even mugenhook
