### ISSUE TITLE
joypad input problem

### ISSUE THREAD

**Issue by Tabris666** [ermaccer/mugenhook#14]
Well i normally use joypad on anything related to games on windows,i updated mugenhook after a while but latest version won't let me use my gamepad since will press random movements it seem an error while coding since previous version works fine all the inputs are correct unlike latest version since will move the joypad random even if no one is pressing buttons.
I use a generic usb joypad but even ps4 and xbox30 gamepad have the same problem.

**Comment by ermaccer** [comment]
Have you tried remapping your controller? 
Tested this thing myself, and yes, buttons are messed up. I remapped controls in the options menu and it seems to fix this.

**Comment by Tabris666** [comment]
each time you exit the game the controls mess up once you restart

**Comment by ermaccer** [comment]
Use the built in save option in menu, if it doesn't save, then it might be in a protected folder you don't have write to access.
