### ISSUE TITLE
[SOLVED] I cant run mugenhook after UPDATING WINDOWS 10

### ISSUE THREAD

**Issue by NachoDVQ** [ermaccer/mugenhook#18]
Hi, 
I have problems trying to run mugenhook after updating windows 10.
ASI loader works, but fails to start mugenhook.asi.

![asdasdasd](https://user-images.githubusercontent.com/73151091/96535011-4f854e80-1267-11eb-8b86-e7c30d9198c7.png)

That's what the mugen window is telling me now. Does not start.
Please help.

I already tried creating a rule in the antivirus, and it still doesn't want to work.

Sorry my english! i try my best.

**Comment by NachoDVQ** [comment]
Ultimate ASI Loader Crash Log

Unhandled exception at 0x66F2DAB2 in MugenHook.asi (+0xdab2): 0xC0000005: Access violation reading location 0x00011E98.
    Register dump:
        EAX: 0x00000000  EBX: 0x76453F20  ECX: 0x00000000  EDX: 0x00000000  
        EDI: 0x764D22A0  ESI: 0x76CE04C0  EBP: 0x0019F88C  EIP: 0x66F2DAB2  
        ESP: 0x0019F050  EFL: 0x00010216  
        
        CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   
        ES: 0x0000002B   DS: 0x0000002B   
        
        ST00: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        ST01: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        ST02: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        ST03: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        ST04: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        ST05: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        ST06: 0x00000000 0x80000000 0x00003FFF 0x00000000  [ 0.000000 -0.000000 0.000000 0.000000 ]
        ST07: 0x00000000 0x00000000 0x00000000 0x002B0000  [ 0.000000 0.000000 0.000000 0.000000 ]
        
        XMM00: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM01: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM02: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM03: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM04: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM05: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM06: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        XMM07: 0x00000000 0x00000000 0x00000000 0x00000000  [ 0.000000 0.000000 0.000000 0.000000 ]
        
    Stack dump:
        0x0019F050:  66F31934 66F317AC 66F20000 00000002 00000001 00000000
        0x0019F068:  00000040 00619108 00619110 01010000 00601570 02010000
        0x0019F080:  00000048 00000000 06000006 00010000 005F0270 00889990
        0x0019F098:  12000012 00000000 00000012 005F0270 0061910F 77896244
        0x0019F0B0:  00618C40 0019F270 77889990 F50DB366 FFFFFFFE 0019F158
        0x0019F0C8:  778557FE 00000100 00000108 005F0328 0019F12C 00000080
        0x0019F0E0:  005F0000 00040021 00618838 00618C40 00614A00 005F0000
        0x0019F0F8:  0000007F 0019F118 77858786 00000000 00000000 77896244
        0x0019F110:  005F96D0 005F0000 00000002 0019F134 76A7149B 00000021
        0x0019F128:  00618C40 00000003 00000064 00000000 005F9CB8 00000013
        base: 0x000A0000   top: 0x0019F050   bottom: 0x001A0000
        
    Backtrace (may be wrong):
        =>0x66F2DAB2 in MugenHook.asi (+0xdab2) (0x0019F88C) 
          0x659B9D76 XShowGameInviteUI+0xdc06 in DDRAW.DLL (+0x19d76) (0x0019F9CC) 
          0x659C025B XShowGameInviteUI+0x140eb in DDRAW.DLL (+0x2025b) (0x0019FD70) 
          0x659BB215 XShowGameInviteUI+0xf0a5 in DDRAW.DLL (+0x1b215) (0x0019FDE4) 
          0x659C04D1 XShowGameInviteUI+0x14361 in DDRAW.DLL (+0x204d1) (0x0019FE18) 
          0x659B8BCC XShowGameInviteUI+0xca5c in DDRAW.DLL (+0x18bcc) (0x0019FE24) 
          0x004DD09D in Mortal Kombat project.exe (+0xdd09d) (0x0019FE60) 
          0x004DD341 in Mortal Kombat project.exe (+0xdd341) (0x0019FEE0) 
          0x004DC68A in Mortal Kombat project.exe (+0xdc68a) (0x0019FF70) 
          0x76CDFA29 BaseThreadInitThunk+0x19 in KERNEL32.DLL (+0x1fa29) (0x0019FF80) 
          0x778775F4 RtlGetAppContainerNamedObjectPath+0xe4 in ntdll.dll (+0x675f4) (0x0019FFDC) 
          0x778775C4 RtlGetAppContainerNamedObjectPath+0xb4 in ntdll.dll (+0x675c4) (0x0019FFEC)

**Comment by ermaccer** [comment]
https://github.com/ermaccer/mugenhook/releases/tag/0.5.4b3

Should be working now, please try.

**Comment by NachoDVQ** [comment]
> https://github.com/ermaccer/mugenhook/releases/tag/0.5.4b3
> 
> Should be working now, please try.

Working, thanks a lot!
