### ISSUE TITLE
Am I missing files?

### ISSUE THREAD

**Issue by Eezy5** [ermaccer/mugenhook#19]
I Just downloaded mugenhook and installed in a new 1.1 mugen but after taking the steps to install from the wiki I get this erreor message when I try to run the new mugen. Failed! Tried to open: cfg\frameloader.dat coming from an eAnimated Portraits. Am I missing system files?

**Comment by ermaccer** [comment]
Are you using latest update? Note that update is a patch for 0.5.4 and doesn't contain all files.

**Comment by Eezy5** [comment]
Ok, Thanks Ermaccer, I just downloaded the master mugenhoo file.
