### ISSUE TITLE
Repeated sound in Training mode

### ISSUE THREAD

**Issue by ermaccer** [ermaccer/mugenhook#2]
Custom cursor sound will repeat because it uses first cursor placement.
To fix, second cursor placement data is required.

**Comment by Eduard-Moraes** [comment]
Sorry, I didn't get it straight, you mean add something to system.def? what would it be ??

**Comment by ermaccer** [comment]
Fixed. Watch mode has been restricted to Player 1 only (p2 will play default system.def sound), requires more research to fix that but is there a reason?
