### ISSUE TITLE
Failed to load the cfg

### ISSUE THREAD

**Issue by NightStarX** [ermaccer/mugenhook#22]
Getting the error "Failed! Could not open mugen.cfg!"

The cfg is in the right place, it works perfectly fin without mugenhook installed, and there's no errors, but it's still giving me this error and not doing anything.

I'm using a screenpack if that changes anything. I mean it shouldn't, but outside of that, I have no idea what could be causing this error and for it to refuse to load mugen.cfg

**Comment by ermaccer** [comment]
It looks for it in the data\mugen.cfg folder, perhaps some path issue?
Is your game directory using any non english characters?

**Comment by NightStarX** [comment]
It's definitely in the data folder where it should be, and it seems to be entirely English.  I'm just kind of baffled why it keeps saying it can't open mugen.cfg, when it's right there, and and there seems to be nothing wrong with it, no non-english characters and nothing to get in the way of the path. When removing Mugenhook entirely, everything is fine, but when putting mugenhook back in, it suddenly cannot find it.

Is there any way to see or change what the eSystem::Init is looking for or what it's pointing to, to make sure? Becuase otherwise, i'm stumped as to what to do about it.

**Comment by ermaccer** [comment]
No idea what's going on for you, have you tried running some game that already uses mugenhook?
