### ISSUE TITLE
I hope it can be repaired

### ISSUE THREAD

**Issue by master-2077** [ermaccer/mugenhook#23]
There is a problem with the cursor sound in the viewing mode. If you choose to play the sound normally on the left, the sound will not play on the right. I hope it can be fixed. There are also problems with variants. After P1 selects characters, when P2 switches characters under the same grid, the image of P1 will also change with the characters switched by P2.

**Comment by ermaccer** [comment]
Watch (viewing) mode abuses P1 cursor for everything, this is the best I can do - play 1 side custom sound only, second side will need to use default as I can't read the character from second cursor in Watch mode.

That's not really MugenHook issue, it's how M.U.G.E.N works. It doesn't display sprites seperately, both images share same pointer. I would need to reverse select screen more to somehow make each sprite use seperate pointers.

**Comment by master-2077** [comment]
好的，原来如此，期待变体的更新
