### ISSUE TITLE
Mugen closes when variants are used

### ISSUE THREAD

**Issue by Twours2** [ermaccer/mugenhook#25]
When I activate the variations option in mugenhook.cfg and try opening mugen it just closes with no explanation, Wich is kinda weird since I have already done this with an older version of mugenhook and on the same screenpack

**Comment by ermaccer** [comment]
Which was the version which you had working? Screenpack name (or if it is custom)?

**Comment by Twours2** [comment]
> Which was the version which you had working? Screenpack name (or if it is custom)?

I actually tested it with two screenpacks/games
Mugen Mix 1.1 and HyperDBZ indigo build
And in both cases the game just closes when the intro vid is skipped, and again, only when the variants option is on

**Comment by ermaccer** [comment]
It indeed crashes with variations on (tested with mix), if you remove the example variations.dat entry it'll work. Have you configured variations or you just ran the game with example line?

**Comment by Twours2** [comment]
> It indeed crashes with variations on (tested with mix), if you remove the example variations.dat entry it'll work. Have you configured variations or you just ran the game with example line?

It crashes with both configured variations and the example line, if the variations.dat doesn't have any entries it runs properly

**Comment by ermaccer** [comment]
https://github.com/ermaccer/mugenhook/releases/

Check latest update, this crash should be fixed.
