### ISSUE TITLE
Very Large Columns crashes MUGEN

### ISSUE THREAD

**Issue by thanguya** [ermaccer/mugenhook#30]
Hi ermaccer, I am having an issue with portraitanimations where if I set my 
rows = 41 and columns = 201 Mugen crashes at the character select. I am aware that you made a fix to a rare crash with large rows, but I am using that version 6.0 and it still crashes. I need columns = 201 for a large screenpack,

This is using a clean Mugen 1.1b and all I did was change rows = 41 and columns = 201 in mugen.cfg and it instantly crashes at the character select screen, when I change back to the default values rows = 4 & columns = 3 everything works and I see KFM animations in the character select screen. I was wondering if there is a workaround or fix for this issue.

**Comment by ermaccer** [comment]
Hi,
Check the 0.6.3 update, I've tested it with your values and it seems to work just fine. 444x4444 also has worked but at very low framerate (obviously). I think this update should kill any further select screen size crashes.

**Comment by thanguya** [comment]
Hi ermaccer, 
Your work ethic is incredible. Thankyou I have tested it on my version of M.U.G.E.N Multiverse and it works as intended now.
