### ISSUE TITLE
Character selection screen with randomselect and empty slots does not load

### ISSUE THREAD

**Issue by lekkoferreira** [ermaccer/mugenhook#31]
Character selection screen with randomselect and empty slots does not load.

In the "select.def" file, I use the letter "X" in each of the slots that I want to be empty, to assemble my layout of my selection screen and in some of the slots, I need "randomselect". It turns out that, using "muenhook", trying to open the selection screen, the log says that mugenhook interprets the letter "X" of the empty slots as if it were a character and does not find the directory of this supposed character, which does not exist. Same with randomselect.

So:

Initializing select screen...finding characters...
   Error reading character file: chars/X/X.def
   Error reading character file: chars/RANDOMSELECT/RANDOMSELECT.def

How to solve this?

P.S. Sorry for my bad english. I'm Brazilian and I'm using Google Translate.

**Comment by ermaccer** [comment]
Check the latest update and see if it helps.
