### ISSUE TITLE
P2 Char Select after 1st selection "stuck"

### ISSUE THREAD

**Issue by TeamHaxley** [ermaccer/mugenhook#34]
I've had this issue using the plugin where, when using 'watch' mode, if player 2 can select more than 1 character, the characters portrait doesn't change from selection 1 when browsing. I haven't deviated from the build or have anything fancy. 

This is most noticeable in 4v4 team battle, where the first character player 2 selects is still visible while trying to select the other 3. 

No errors when loading and I don't see any issues in my animatedportraits.dat. I have 322 characters.

Edit: Isolated the issue to 'Watch' mode

**Comment by ermaccer** [comment]
Watch mode is kinda special and current MugenHook support for it is as good as it can get unfortunately.

**Comment by TeamHaxley** [comment]
Acceptable, to be blunt. You've done exceptional work and this is a
non-issue in the grand scheme.

Thank you for your work which has really increased the QoL of the mugen
community, and me personally. You rock!
