### ISSUE TITLE
Automatic setting for characters that don't have variations already defined?

### ISSUE THREAD

**Issue by ObsidianPlague** [ermaccer/mugenhook#35]
If characters are left undefined in the .dat, it screws with selecting characters.

It shouldn't be necessary to have to define variations for characters that don't have any, especially for potential setups with hundreds of characters.
Maybe automatically set characters to use one variation with the one variation being itself if it's not defined in the .dat?

**Comment by ermaccer** [comment]
There's no need to define variation entries for characters who won't have them, are you sure this is not some other issue?

**Comment by ObsidianPlague** [comment]
Now that I think about it, it may be randomselects screwing with it.
I select one character with no variation and it picks the entirely wrong character.
